layers:
  default:
  - [TAB, Q, W, E, R, T, Y, U, I, O, P, BSPC]
  - [LCTRL, A, S, D, F, G, H, J, K, L, ;, '''']
  - [LSHFT, Z, X, C, V, B, N, M, ',', ., /, ESC]
  - [LGUI, lower, SPACE, RET, raise, LALT]
  lower:
  - [TAB, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', DEL]
  - [LCTRL, '', '', '', '', '', HOME, LEFT, UP, DOWN, RIGHT, END]
  - [LSHFT, '', '', '', '', '', '', '', PG UP, PG DN, '', '']
  - [LGUI, '', SPACE, RET, func, LALT]
  raise:
  - [TAB, '!', '@', '#', $, '%', ^, '&', KP MULTIPLY, (, ), DEL]
  - [LCTRL, QUOT, RA(5), '', '', '', '-', '=', '[', ']', \, '`']
  - [LSHFT, '', '', '', '', '', _, +, '{', '}', '|', '~']
  - [LGUI, func, SPACE, RET, '', LALT]
  func:
  - [TAB, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, DEL]
  - [LCTRL, F11, F12, F13, F14, F15, BRI DN, BRI UP, VOL DN, VOL UP, PP, NEXT]
  - [LSHFT, '', '', '', '', '', '', '', BT 0, BT 1, BT 2, BT CLR]
  - [LGUI, '', SPACE, RET, '', LALT]
