layout:
  ortho_layout:
    split: true
    rows: 3
    columns: 6
    thumbs: 3
layers:
  default:
  - [TAB, Q, W, E, R, T, Y, U, I, O, P, BSPC]
  - [LCTRL, A, S, D, F, G, H, J, K, L, ;, '''']
  - [LSHFT, Z, X, C, V, B, N, M, ',', ., /, ESC]
  - [LGUI, lower, SPACE, RET, raise, RALT]
  lower:
  - [TAB, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', BSPC]
  - [LCTRL, '', '', '', '', '', HOME, LEFT, DOWN, UP, RIGHT, END]
  - [LSHFT, '', '', '', '', '', '', '', PG DN, PG UP, '', '']
  - [LGUI, '', SPACE, RET, func, RALT]
  raise:
  - [TAB, '!', '@', '#', $, '%', ^, '&', KP MULTIPLY, (, ), BSPC]
  - [LCTRL, '', '', '', '', '', '-', '=', '[', ']', \, '`']
  - [LSHFT, '', '', '', '', '', _, +, '{', '}', '|', '~']
  - [LGUI, func, SPACE, RET, '', RALT]
  func:
  - [TAB, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, BSPC]
  - [LCTRL, F11, F12, F13, F14, F15, '', BT 0, BT 1, BT 2, '', BT CLR]
  - [LSHFT, '', '', '', '', '', '', OUT USB, OUT BLE, OUT TOG, '', '']
  - [LGUI, '', SPACE, RET, '', RALT]
